In [ ]:
import numpy as np
import pandas as pd

In [ ]:
persona_df = pd.read_csv('student_personas.csv')
display(persona_df.head(2))
grade_df = pd.read_csv('grade_final.csv')
display(grade_df.head(2))
attendance_df = pd.read_csv('monthly_subject_attendance.csv')
display(attendance_df.head(2))
back_df = pd.read_csv('student_backlogs_v2.csv')
display(back_df.head(2))

  studentID        persona
0     E0001  Fast learners
1     E0002  Fast learners

,studentID,persona,Current_CGPA,CourseID,Quiz_1,Quiz_2,Quiz_3,Midterm
0,E0001,Fast learners,9.07,CSET243,52,75,93,72
1,E0001,Fast learners,9.07,CSET240,88,88,77,96

  studentID CourseID   Month  Attendance_Percentage
0     E0001  CSET243    July                     95
1     E0001  CSET243  August                     98

  studentID Course_code  Backlog        persona
0     E0001     CSET243        0  Fast learners
1     E0001     CSET240        0  Fast learners

WARNING: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('Course_code').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Backlog']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Backlog'}, axis=1)
              .sort_values('Backlog', ascending=True))
  xs = counted['Backlog']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values('Backlog', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Course_code')):
  _plot_series(series, series_name, i)
  fig.legend(title='Course_code', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Backlog')
_ = plt.ylabel('count()')

#agregate grades data

In [ ]:
# Define the columns containing marks
marks_cols = ['Quiz_1', 'Quiz_2', 'Quiz_3', 'Midterm']

# Calculate the average score for each course
grade_df['Course_Performance_Score'] = grade_df[marks_cols].mean(axis=1)

# Now, group by student and calculate their average score across all courses
student_grades_agg = grade_df.groupby('studentID')['Course_Performance_Score'].mean().reset_index()
student_grades_agg = student_grades_agg.rename(columns={'Course_Performance_Score': 'Semester_Performance_Score'})

print("--- Aggregated Student Grades ---")
print(student_grades_agg)

--- Aggregated Student Grades ---
     studentID  Semester_Performance_Score
0        E0001                     83.0000
1        E0002                     82.2500
2        E0003                     75.6250
3        E0004                     48.8125
4        E0005                     79.2500
...        ...                         ...
4995     E4996                     46.8750
4996     E4997                     75.6875
4997     E4998                     79.9375
4998     E4999                     54.2500
4999     E5000                     84.0625

[5000 rows x 2 columns]

## Aggregate Attendance data

In [ ]:
import pandas as pd

# 1. DEFINE the DataFrame first
# This creates the sample attendance data.
# If you have an Excel file, you would use: attendance_df = pd.read_excel('your_file.xlsx')
attendance_data = {
    'studentID': ['E0001', 'E0001', 'E0001', 'E0002', 'E0002'],
    'CourseID': ['CSET243', 'CSET243', 'CSET240', 'CSET243', 'CSET250'],
    'Month': ['July', 'August', 'July', 'July', 'August'],
    'Attendance_Percentage': [95, 98, 92, 65, 70]
}
attendance_df = pd.DataFrame(attendance_data)


# 2. NOW, run your aggregation code
# This part of your code is correct, it just needed the DataFrame to exist.
student_attendance_agg = attendance_df.groupby('studentID')['Attendance_Percentage'].mean().reset_index()
student_attendance_agg = student_attendance_agg.rename(columns={'Attendance_Percentage': 'Avg_Attendance_Percentage'})


# 3. Print the result
print("--- Aggregated Student Attendance ---")
print(student_attendance_agg)

--- Aggregated Student Attendance ---
  studentID  Avg_Attendance_Percentage
0     E0001                       95.0
1     E0002                       67.5

# Aggregate Backlogs data

In [ ]:
import pandas as pd

# 1. Define the backlog_df DataFrame
backlog_data = {
    'studentID': ['E0001', 'E0001', 'E0002', 'E0002'],
    'Course_code': ['CSET243', 'CSET240', 'CSET243', 'CSET250'],
    'Backlog': [0, 0, 1, 0],
    'persona': ['Fast learners', 'Fast learners', 'Slow learners', 'Slow learners']
}
backlog_df = pd.DataFrame(backlog_data)

# 2. Now, you can run the aggregation code on the defined DataFrame
student_backlog_agg = backlog_df.groupby('studentID')['Backlog'].sum().reset_index()
student_backlog_agg = student_backlog_agg.rename(columns={'Backlog': 'Total_Backlogs'})

print("\n--- Aggregated Student Backlogs ---")
print(student_backlog_agg)

--- Aggregated Student Backlogs ---
  studentID  Total_Backlogs
0     E0001               0
1     E0002               1

# Final Aggregated **Data**

In [ ]:
import pandas as pd

# Recreating the three aggregated DataFrames from Step 1
student_grades_agg = pd.DataFrame({
    'studentID': ['E0001', 'E0002'],
    'Semester_Performance_Score': [83.25, 53.25]
})

student_attendance_agg = pd.DataFrame({
    'studentID': ['E0001', 'E0002'],
    'Avg_Attendance_Percentage': [95.0, 67.5]
})

student_backlog_agg = pd.DataFrame({
    'studentID': ['E0001', 'E0002'],
    'Total_Backlogs': [0, 1]
})

# We also need the original grades_df to get the main student info
grades_data = {
    'studentID': ['E0001', 'E0001', 'E0002', 'E0002'],
    'persona': ['Fast learners', 'Fast learners', 'Slow learners', 'Slow learners'],
    'Current_CGPA': [9.07, 9.07, 6.50, 6.50]
}
grades_df = pd.DataFrame(grades_data)
final_df

,studentID,persona,Current_CGPA,Semester_Performance_Score,Avg_Attendance_Percentage,Total_Backlogs
0,E0001,Fast learners,9.07,83.25,95.0,0
1,E0002,Slow learners,6.50,53.25,67.5,1

In [ ]:
import pandas as pd

# --- Prerequisite Data (Recreating the aggregated tables) ---
student_info_df = pd.DataFrame({
    'studentID': ['E0001', 'E0002'],
    'persona': ['Fast learners', 'Slow learners'],
    'Current_CGPA': [9.07, 6.50]
})
student_grades_agg = pd.DataFrame({
    'studentID': ['E0001', 'E0002'],
    'Semester_Performance_Score': [83.25, 53.25]
})
student_attendance_agg = pd.DataFrame({
    'studentID': ['E0001', 'E0002'],
    'Avg_Attendance_Percentage': [95.0, 67.5]
})
student_backlog_agg = pd.DataFrame({
    'studentID': ['E0001', 'E0002'],
    'Total_Backlogs': [0, 1]
})


# --- Merging into the final DataFrame ---
final_df = pd.merge(student_info_df, student_grades_agg, on='studentID', how='left')
final_df = pd.merge(final_df, student_attendance_agg, on='studentID', how='left')
final_df = pd.merge(final_df, student_backlog_agg, on='studentID', how='left')


# --- Printing the final result ---
print("--- Final Merged & Aggregated Student Data ---")
print(final_df)

--- Final Merged & Aggregated Student Data ---
  studentID        persona  Current_CGPA  Semester_Performance_Score  \
0     E0001  Fast learners          9.07                       83.25
1     E0002  Slow learners          6.50                       53.25

   Avg_Attendance_Percentage  Total_Backlogs
0                       95.0               0
1                       67.5               1

# Merge into a Single Master **Table**
Unique Student Info Table

In [ ]:
# Select essential columns and remove duplicate entries for each student
student_info_df = grades_df[['studentID', 'persona', 'Current_CGPA']].drop_duplicates()

print("--- Unique Student Info Table ---")
print(student_info_df)

--- Unique Student Info Table ---
  studentID        persona  Current_CGPA
0     E0001  Fast learners          9.07
2     E0002  Slow learners          6.50

# Sequentially Merge the Aggregated ***Data***

In [ ]:
# 1. Merge the student info with aggregated grades
final_df = pd.merge(student_info_df, student_grades_agg, on='studentID', how='left')

# 2. Merge the result with aggregated attendance
final_df = pd.merge(final_df, student_attendance_agg, on='studentID', how='left')

# 3. Merge the result with aggregated backlogs
final_df = pd.merge(final_df, student_backlog_agg, on='studentID', how='left')

print("\n--- Final Merged DataFrame ---")
print(final_df)

--- Final Merged DataFrame ---
  studentID        persona  Current_CGPA  Semester_Performance_Score  \
0     E0001  Fast learners          9.07                       83.25
1     E0002  Slow learners          6.50                       53.25

   Avg_Attendance_Percentage  Total_Backlogs
0                       95.0               0
1                       67.5               1

# **Merging the two semesters**

In [ ]:
import pandas as pd

# This is the DataFrame you already have from the current semester
current_semester_df = pd.DataFrame({
    'studentID': ['E0001', 'E0002', 'E0003'],
    'Current_CGPA': [9.07, 6.50, 7.20],
    'Avg_Attendance_Percentage': [95.0, 67.5, 75.0],
    'Total_Backlogs': [0, 1, 3]
})

# This is the data you generate from the PREVIOUS semester's files
previous_semester_df = pd.DataFrame({
    'studentID': ['E0001', 'E0002', 'E0003'],
    'Current_CGPA': [8.95, 6.95, 7.30],
    'Avg_Attendance_Percentage': [96.0, 85.0, 76.0],
    'Total_Backlogs': [0, 0, 3]
})

In [ ]:
# Merge the two dataframes on the studentID
# The suffixes distinguish between the current and previous semester's data
trend_df = pd.merge(
    current_semester_df,
    previous_semester_df,
    on='studentID',
    suffixes=('_current', '_previous')
)

print("--- Merged Semester Data ---")
print(trend_df)

--- Merged Semester Data ---
  studentID  Current_CGPA_current  Avg_Attendance_Percentage_current  \
0     E0001                  9.07                               95.0
1     E0002                  6.50                               67.5
2     E0003                  7.20                               75.0

   Total_Backlogs_current  Current_CGPA_previous  \
0                       0                   8.95
1                       1                   6.95
2                       3                   7.30

   Avg_Attendance_Percentage_previous  Total_Backlogs_previous
0                                96.0                        0
1                                85.0                        0
2                                76.0                        3

# TREND **FEATURES**

In [ ]:
# Calculate the difference between current and previous semester metrics
trend_df['CGPA_Trend'] = trend_df['Current_CGPA_current'] - trend_df['Current_CGPA_previous']
trend_df['Attendance_Trend'] = trend_df['Avg_Attendance_Percentage_current'] - trend_df['Avg_Attendance_Percentage_previous']
trend_df['Backlog_Trend'] = trend_df['Total_Backlogs_current'] - trend_df['Total_Backlogs_previous']

print("\n--- Data with Trend Features ---")
print(trend_df)

--- Data with Trend Features ---
  studentID  Current_CGPA_current  Avg_Attendance_Percentage_current  \
0     E0001                  9.07                               95.0
1     E0002                  6.50                               67.5
2     E0003                  7.20                               75.0

   Total_Backlogs_current  Current_CGPA_previous  \
0                       0                   8.95
1                       1                   6.95
2                       3                   7.30

   Avg_Attendance_Percentage_previous  Total_Backlogs_previous  CGPA_Trend  \
0                                96.0                        0        0.12
1                                85.0                        0       -0.45
2                                76.0                        3       -0.10

   Attendance_Trend  Backlog_Trend
0              -1.0              0
1             -17.5              1
2              -1.0              0

**Final Model Ready Dataset**

In [ ]:
# Select the most important columns for your final dataset
final_model_df = trend_df[[
    'studentID',
    'Current_CGPA_current',
    'Avg_Attendance_Percentage_current',
    'Total_Backlogs_current',
    'CGPA_Trend',
    'Attendance_Trend',
    'Backlog_Trend'
]]

# Rename current columns for clarity
final_model_df = final_model_df.rename(columns={
    'Current_CGPA_current': 'Current_CGPA',
    'Avg_Attendance_Percentage_current': 'Current_Attendance',
    'Total_Backlogs_current': 'Current_Backlogs'
})


print("\n--- Final Model-Ready Dataset ---")
print(final_model_df)

--- Final Model-Ready Dataset ---
  studentID  Current_CGPA  Current_Attendance  Current_Backlogs  CGPA_Trend  \
0     E0001          9.07                95.0                 0        0.12
1     E0002          6.50                67.5                 1       -0.45
2     E0003          7.20                75.0                 3       -0.10

   Attendance_Trend  Backlog_Trend
0              -1.0              0
1             -17.5              1
2              -1.0              0